# Generated by Django 2.2 on 2020-05-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Howto', 'How to accomplish tasks'), ('News', 'Tech News'), ('Articles', 'Tech and Programming articles')], max_length=50),
        ),
    ]
