# Generated by Django 2.2 on 2020-05-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
