# Generated by Django 2.2 on 2020-07-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover',
        ),
    ]
